### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by xmha97** [deltazefiro/Amarok-Hider#10]
Please add this app to F-Droid.

**Comment by deltazefiro** [comment]
Maybe you can download Amarok from [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/deltazero.amarok.foss), an F-Droid Repository maintained by [@IzzySoft](https://github.com/IzzySoft).

**Comment by xmha97** [comment]
Yes, I came across this app through IzzyOnDroid. But I want the app to be added in the main repository.

**Comment by deltazefiro** [comment]
Hmm... That's somehow embarrassing... :thinking:   
I put it on IzzyOnDroid just recently (#2), and it seems that if the app is added to the main repo, IzzyOnDroid has to take it down from its repo according to their [removal principle](https://apt.izzysoft.de/fdroid/index/info).

**Comment by xmha97** [comment]
If you put your app in the main repository, more people will see it because your app is in F-Droid by default and you don't need to add a repository.

There are also several apps that are in both repositories:

# 1. LibreTube

https://f-droid.org/en/packages/com.github.libretube

https://apt.izzysoft.de/fdroid/index/apk/com.github.libretube

# 2. IzzyOnDroid

https://f-droid.org/packages/in.sunilpaulmathew.izzyondroid

https://apt.izzysoft.de/fdroid/index/apk/in.sunilpaulmathew.izzyondroid

**Comment by deltazefiro** [comment]
Well, in that case, I'll put Amarok in the main repository as soon as possible.  
Thanks for your work!

**Comment by xmha97** [comment]
Thank you.

**Comment by deltazefiro** [comment]
Hey @xmha97 :clap: 
Done! See [here](https://f-droid.org/packages/deltazero.amarok.foss/).

**Comment by xmha97** [comment]
Thanks.
Why is this app signed by you?

![Screenshot_2023-02-04-11-58-30-935_io.github.muntashirakon.AppManager.jpg](https://user-images.githubusercontent.com/23485114/216757400-2dc03e2a-9bcd-4aeb-ad53-793ce58da1cc.jpg)

All F-Droid apps signed by F-Droid.
For example, see the F-Droid version of the Wikipedia app.

![Screenshot_2023-02-04-11-58-43-123_io.github.muntashirakon.AppManager.jpg](https://user-images.githubusercontent.com/23485114/216757392-b159c165-943c-4c3a-a282-b9b593b528ad.jpg)

**Comment by deltazefiro** [comment]
> Why is this app signed by you?

F-droid just introduced [Reproducible Builds](https://f-droid.org/docs/Reproducible_Builds/) recently.

**Comment by xmha97** [comment]
Thanks for saying that, that's a good thing.

**Comment by deltazefiro** [comment]
Close the issue then.
