### ISSUE TITLE
[FeatureRequest] Hold GitHub repository link to copy

### ISSUE THREAD

**Issue by jcperil** [deltazefiro/Amarok-Hider#101]
**Feature Description / 功能描述**
A link to the GitHub repositiry is embedded in the welcome screen. Requesting a feature that allows you to press and hold the link to copy it into your clipboard.

<img src="https://github.com/deltazefiro/Amarok-Hider/assets/89805719/226ec4d2-625f-4a82-b9dc-952a3f626ea2" height="250px"/>

**Reason / 理由**
Opsec. It is better to know the URL before opening it.

**Suggest Solution / 实现方案**
Able to copy link by long pressing **GitHub repository**.

**Comment by deltazefiro** [comment]
Hi @jcperil :clap:   

Personally I do not think it is necessary. The word _GitHub repository_ implies that the corresponding open page should be something like https://github.com/somebody/repo. Additionally, the vanilla Android alert dialog does not support detecting long press button actions.
