### ISSUE TITLE
Improve landscape mode

### ISSUE THREAD

**Issue by xmha97** [deltazefiro/Amarok-Hider#11]
Please improve the landscape mode.

![Screenshot_2022-12-30-02-55-41-953_deltazero.amarok.foss.jpg](https://user-images.githubusercontent.com/23485114/210020634-b0e7fabc-26ff-49a3-b3f1-f38600bbe9b2.jpg)

**Comment by deltazefiro** [comment]
Try the latest [pre-release](https://github.com/deltazefiro/Amarok-Hider/releases/tag/v0.8.1b2).  
Made some improvements on the MainActivity.  
Happy New Year!

**Comment by deltazefiro** [comment]
Let's mark this issue as resolved.
