### ISSUE TITLE
[FeatureRequest] add quick-setting tile for hiding files

### ISSUE THREAD

**Issue by formula-spectre** [deltazefiro/Amarok-Hider#112]
**Feature Description / 功能描述**
Add a tile for android's drop down menu quick settings

**Reason / 理由**
i think it's handier than a persistent notification imo

**Suggest Solution / 实现方案**
obviously keep the two!

**Comment by deltazefiro** [comment]
Hi @formula-spectre 
We've already had a quick setting tile :D  
Just click on the edit icon in the quick settings panel and check "Available toggles" - you'll find it there.

**Comment by formula-spectre** [comment]
me blind apparently, apologies!
