### ISSUE TITLE
[FeatureRequest] Tweak not hidden reminder message

### ISSUE THREAD

**Issue by CanglanXYA** [deltazefiro/Amarok-Hider#114]
**Feature Description / 功能描述**
A clear and concise description of what you want to happen. / 请描述你想建议加入的新功能。
Change the reminder words "Your privacy is not hidden" to something else that is not so suspicious like pretending to some social media info or music player controller. Depend on the app's logo, maybe it can pretend to be a workout app or hiking app.

**Reason / 理由**
Please describe why this feature should be added. / 请描述为什么应该加入这个功能。
It's suspicious for a "calender" app to have that reminder....

**Suggest Solution / 实现方案**
(Optional) Possible ways to implement this feature / （可选）如果你已想出新功能的实现方案，请在这里写出。

**Comment by CanglanXYA** [comment]
Maybe you can generate a series of message in a list and let the amarok randomly chooses one after we try to click the hide bottom.

**Comment by deltazefiro** [comment]
Hi @CanglanXYA :clap:   
Thanks for your input. 
Please note, the notification is not visible when Amarok is hidden. Its purpose is to remind *you* to hide – meaning, it's intended for your eyes only, not for others to see. :P

**Comment by CanglanXYA** [comment]
> Hi @CanglanXYA 👏 The notification is not visible when Amarok is hidden. Its purpose is to remind _you_ to hide – meaning, it's intended for your eyes only, not for others to see. :P

Thx for that :), I forgot its at unhidden situation
