### ISSUE TITLE
[BUG] Obfuscation (Encryption And Decryption) Bug.

### ISSUE THREAD

**Issue by atikattar1104** [deltazefiro/Amarok-Hider#121]
# Description :- 

When It Comes To Large Amount Of Files And Folders (Approx. More Than 750MB), 

1. Most Files And Folders Are Encrypted And Obfuscated Properly, But Only Some Files And Folders (Very Small Number Of Them) Are Left Untouched, Leaving Them Vulnerable To Direct Access. 

2. Same For Decryption, Most Files And Folders Are Decrypted And Deobfuscated Properly, But Some Files And Folders (Very Small Number Of Them) Are Left Untouched, Leaving Them Inaccessible To Normal User. 

This Only Happens Occasionally (Once In 50-100 Times Of Hiding And Unhiding). Otherwise Works Normally.

This Also Applies To Folders With Huge Number Of Subdirectories.

# Steps to reproduce the behavior :- 

Reproduction Not Possible, Since Occasional Occurence Of Bugs.

# Expected behavior :- 

If Large Amount Of Files, And Folders With Large Amount Of Subdirectories Are Supported, All Files And Folders Should Be Obfuscated And Deobfuscated, Without A Bug Like This.

# Basic Information :- 

 - Phone :- Redmi 7A
 - OS (ROM) :- Android 10, MIUI 12.5
 - Amarok Version :- v0.8.5b3 F-Droid Release.

Additional context :- 

The Only Workaround To Fix The Affected Files And Folders Is To 

In Case Of "1." :- 

Hide Them On Different Folder, Then Move Or Copy The Obfuscated Data To Folder With Large Data, To Store Data At It's Original Space.

In Case Of "2." :- 

Move Or Copy The Failed Unhide Operation's Obfuscated Data To Different Folder, Then Re Perform Unhide Operation, To Make Original Data Accessible Again.

**Comment by deltazefiro** [comment]
Hi @atikattar1104 👏, thank you for bringing this to my attention.

Two likely explanations:
1. A file or folder with the same name might already exist in the specified path. i.e. if you obfuscated a file named `log.txt` to `a3hdjj!amk`, and another application creates a new file named `log.txt` in the same folder, there will be a conflict when Amarok attempts to revert `a3hdjj!amk` back to `log.txt`, as a file with that name already exists.
2. The obfuscated name could be excessively long. Amarok use base64 encoding for filenames, which can result in longer obfuscated names. This might surpass the maximum filename length allowed for Android files.

If you could provide logs at the time of the issue, it would help me identify the issue more effectively :D

**Comment by atikattar1104** [comment]
Oh! Ok. I Think The First One Might Be The Reason Of This Issue. I Actually Was Trying To Hide The Folder Which Does Actually Have Files With Same Name. Probably That's Why This Happens.

I Will Try To Recreate The Same With Test Data, And Extract The Logs For The Same.
