### ISSUE TITLE
[BUG] 在多亲F21pro+使用shizuku激活隐藏解除后无法正确显示图标

### ISSUE THREAD

**Issue by Beluga0101** [deltazefiro/Amarok-Hider#125]
**Describe the bug / 问题描述**
在多亲F21pro+使用shizuku激活隐藏解除后无法正确显示图标

**To Reproduce / 复现步骤**
1.使用shizuku激活 
2. 添加隐藏应用
3. 隐藏应用
4. 解除隐藏
5. 返回桌面
6. 故障发生

**Expected behavior / 预期行为**
隐藏时不显示应用，结束隐藏后显示

**Screenshots / 截图**
（可选）问题复现时候的截图或录屏。

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: [e.g.qin5.3.2 ]
 - Android Version / 安卓版本: [e.g. 11]
 - Amarok Version / Amarok版本: [e.g. v0.8.5b3]

**Additional context / 其他信息**
在这里输入其他有关此异常的信息。

**Comment by deltazefiro** [comment]
感谢反馈。
Amarok调用系统包管理器进行应用隐藏。第三方ROM桌面可能未遵循AOSP相应规范，结束隐藏时无法正常显示图标。
抱歉我无法解决这个问题，请向ROM开发者反馈。
