### ISSUE TITLE
[FeatureRequest] Hide by tapping notification

### ISSUE THREAD

**Issue by hiddense** [deltazefiro/Amarok-Hider#140]
Despite the notification saying "Click to hide" clicking it opens Amarok for you to click hide in it, and can be cumbersome if you set a password before.

Can you make an option for hiding without prompt after tapping it? Seems to be an intended behaviour, but if not a toggle for both options would be great.

Thank you for creating this app.

**Comment by deltazefiro** [comment]
Apologize for the late response. I've added a button to the notification for hiding.
