### ISSUE TITLE
[BUG] There is no trigger on media rescan after .nomedia hide/unhide method

### ISSUE THREAD

**Issue by FinecoFinit** [deltazefiro/Amarok-Hider#146]
**Describe the bug / 问题描述**
Media is still visible after adding .nomedia file

**Expected behavior / 预期行为**
.nomedia file should be created and media rescan called

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: Oxygen OS 11
 - Android Version / 安卓版本: 11
 - Amarok Version / Amarok版本: v0.8.6b1

**Comment by deltazefiro** [comment]
Apologize for the late response.  Made a fix.  
Please try out [this](https://github.com/deltazefiro/Amarok-Hider/actions/runs/8763556402/artifacts/1431743519) version.

**Comment by FinecoFinit** [comment]
@deltazefiro Works! But media store might be slow on rescan, I switch the app and pictures still there for a few seconds, I think better add progress bar until media store rescan finishes its job

**Comment by deltazefiro** [comment]
> I think better add progress bar until media store rescan finishes its job

I prefer to keep it quiet in the background. The media store scanning process is carried out by the system, not Amarok. Amarok only sends a message to the system to trigger the rescan. Adding a progress bar in Amarok that shows the system's progress could be misleading and nonintuitive.

**Comment by FinecoFinit** [comment]
Well then, lgtm
