### ISSUE TITLE
[FeatureRequest] 

### ISSUE THREAD

**Issue by samakew** [deltazefiro/Amarok-Hider#149]
A possibility to move any app you have in home screen grid after it's been hid.

after i hid an app, i could not move it in my home screen to any other slot/grid, only way is to reinstall. which isn't so efficient, and would make a huge difference to me.

make it possible to move any hidden apps on home screen while the apps itself are unhidden. im no coder so i dont have a clue if its possible, or if its possible but hard to do, or even easy. but i would be very grateful if it could be done and hope maybe others would also benefit from this <3

**Comment by deltazefiro** [comment]
> after i hid an app, i could not move it in my home screen to any other slot/grid, only way is to reinstall.

I'm sorry but I'm confused - could you provide a screenshot or screencast to clarify your issue? Does that mean the hidden app is still visible on the home screen?

**Comment by samakew** [comment]
The app works as it should, i didn't mean to make an issue request, but an feature request. To be able to move the app wherever i want, when the app is unhidden. :)) <3

Mvh William
________________________________

**Comment by samakew** [comment]
thank you! it certainly did answer my question! thank you for your fast responses and for making this app possible! <3 wish you all the best!!

Mvh William
________________________________
