### ISSUE TITLE
[BUG] 隐藏后老板键不消失

### ISSUE THREAD

**Issue by aaa-qwq-123** [deltazefiro/Amarok-Hider#151]
**Describe the bug / 问题描述**
请清晰地描述您遇到的异常。
锁定Amarok的后台之后在点击老板键隐藏
应用和文件夹成功的隐藏但是老板键不消失
**To Reproduce / 复现步骤**
Steps to reproduce the behavior / 复现异常的步骤:
1. 取消隐藏
2. 锁定后台
3. 删掉后台
4. 隐藏应用
5. 老板键不消失
6. 再次取消隐藏
7. 出现两个老板键

**Expected behavior / 预期行为**
描述您认为正常情况下应该发生什么。
点击老板键后提示已隐藏，然后老板键消失
**Screenshots / 截图**
（可选）问题复现时候的截图或录屏。

https://github.com/deltazefiro/Amarok-Hider/assets/167326689/c65e0820-21c6-4dc1-a261-0d43e2661cfc

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: coloros13
 - Android Version / 安卓版本: 13
 - Amarok Version / Amarok版本: 0.8.7b1

**Additional context / 其他信息**
在这里输入其他有关此异常的信息。

**Comment by deltazefiro** [comment]
感谢反馈。根据您的说明，我无法复现这个问题。在我测试的设备中，只要删后台老板键就会消失，也是符合预期的行为。
我想“锁定后台”这个操作不是导致问题的关键。这个功能并非 Android 原生功能，一般锁定只是一键清后台时不清理此应用。
您能尝试一下不锁定后台，这一问题能否复现吗？

**Comment by deltazefiro** [comment]
Close as stale. Reopen if needed.
