### ISSUE TITLE
[BUG] Amarok : what to choose ? Nothing like to be good on my “POCO X5 Pro”

### ISSUE THREAD

**Issue by sypqys** [deltazefiro/Amarok-Hider#153]
Hello !

How it works ?
When it is an calendar, I don’t know how I came back to the app…

![signal-2024-05-11-132713](https://github.com/deltazefiro/Amarok-Hider/assets/27967268/670de2d2-1356-45bb-a40b-255c5dd8fa25)

**Basic Information (please complete the following information) / 请填写以下信息:**
 - [Xiaomi HyperOS 1.0.3.0.UMSMIXM]
 - Android Version / 安卓版本: [14]
 - Amarok Version / Amarok版本: [v. 0.8.7b1]

**Comment by deltazefiro** [comment]
> what to choose ? Nothing like to be good on my “POCO X5 Pro”

Please read [the docs](https://deltazefiro.github.io/Amarok-doc/en-US/hideapp.html#which-mode-should-i-use).

> When it is an calendar, I don’t know how I came back to the app…

Long press the year number.
