### ISSUE TITLE
[BUG] photos were destroyed in subfolders of a folder while amarok was running

### ISSUE THREAD

**Issue by Wjxfi** [deltazefiro/Amarok-Hider#16]
**Describe the bug / 问题描述**
photos were destroyed in subfolders of a folder while amarok was running

**To Reproduce / 复现步骤**
Steps to reproduce the behavior / 复现异常的步骤:
create a folder with a photo. inside it, create another folder with a photo. inside it, create another folder with a photo. activate amarok. deactivate amarok

**Expected behavior / 预期行为**
The pictures should show up, but they don't.

**Screenshots / 截图**
https://user-images.githubusercontent.com/113500363/210256134-33998793-846f-4d32-a608-031dce18668b.mp4

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: MIUI 12.0.5
 - Android Version / 安卓版本: 12
 - Amarok Version / Amarok版本: v0.8.1b2

Additional information: in the main, first folder, the photos remain intact

**Comment by deltazefiro** [comment]
I've tried several times. I can't reproduce it either :thinking:

**Comment by deltazefiro** [comment]
Made a full refactoring of FileHider. #20  
Perhaps this issue is gone now.

**Comment by deltazefiro** [comment]
Seem that the issue has been resolved.
