### ISSUE TITLE
File hiding crashes on OxygenOS 11

### ISSUE THREAD

**Issue by AwesomeVk47** [deltazefiro/Amarok-Hider#171]
So after updating from v0.8.7 a2, pressing hide does hide the items, but amarock crashes and the next time I open it, it shows the "hide" button instead of the 'unhide" button

Mode: shizuku mode
Shizuku version: 13.5.4.r1049.0e53409

**Comment by catslashbin** [comment]
Hi @AwesomeVk47 
Thanks for reporting. Unfortunately, I can not reproduce this issue with Amarok v0.8.7a2 and Shizuku 13.5.4 on either Android 14 or 13. If you could provide the crash log, I'll be more likely to reproduce it.
You can catch logs with [logcat](https://developer.android.com/tools/logcat).

**Comment by deltazefiro** [comment]
Hi @AwesomeVk47
Thanks for reporting. Unfortunately, I can not reproduce this issue with Amarok v0.8.7a2 and Shizuku 13.5.4 on either Android 14 or 13. If you could provide the crash log, I'll be more likely to reproduce it.
You can catch logs with [logcat](https://developer.android.com/tools/logcat).

**Comment by AwesomeVk47** [comment]
sorry if I was not clear enough, I meant amarok worked fine till v0.8.7a2 after which it started giving problems, here are the logs for v0.9.1.

[logcat.txt](https://github.com/user-attachments/files/16182454/logcat.txt)

**Comment by deltazefiro** [comment]
I checked the log but did not find anything abnormal. There were no crashes or unexpected errors :(

Could you please:
1. Try to reproduce the issue with [this debug version](https://github.com/deltazefiro/Amarok-Hider/actions/runs/9418828265/artifacts/1579519720)
2. Record your screen to show how Amarok crashes

**Comment by AwesomeVk47** [comment]
Here are the files you requested
https://github.com/user-attachments/assets/c7a0a2fc-e422-4504-90c4-b36dd67032af

[logcat 2.txt](https://github.com/user-attachments/files/16187790/logcat.2.txt)

**Comment by deltazefiro** [comment]
You did not get the full log, I'm afraid. I noticed the two log files are both about 1MB.
Try this:
```
adb -d logcat deltazero.amarok.foss:V > log.txt
```

**Comment by AwesomeVk47** [comment]
[Uploading log.txt…]()

**Comment by AwesomeVk47** [comment]
[log.txt](https://github.com/user-attachments/files/16188362/log.txt)

**Comment by deltazefiro** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
  at android.media.MediaScannerConnection.scanFile(MediaScannerConnection.java:237)
  ...
```

I've identified the crash, which matches others tracked. This issue occurs exclusively on OnePlus devices running Android 11, indicating a potential ROM bug. I'll make a workaround, but I would recommend considering a system update.

**Comment by deltazefiro** [comment]
Please try [this](https://github.com/deltazefiro/Amarok-Hider/actions/runs/9905249998/artifacts/1694440084)

**Comment by AwesomeVk47** [comment]
Thank you it works now....there are many reasons I cannot update my phone now, I hope you will release this fix as part of the main releases for the application.

**Comment by deltazefiro** [comment]
> I hope you will release this fix as part of the main releases for the application.

Releasing in v0.9.2.
