### ISSUE TITLE
[Feature] Ability to toggle off toast messages

### ISSUE THREAD

**Issue by Omegaplexx** [deltazefiro/Amarok-Hider#172]
**Feature Description / 功能描述**
Ability to hide "Cock-a-doodle-doo" and "Be careful" toast messages

**Reason / 理由**
These toasts are annoying and can compromise privacy in cases where hiding apps/files needs to be done urgently via the panic button

**Suggest Solution / 实现方案**
Remove the toasts when clicking the hide/show files and apps button or make a setting to hide'em

Thank you

**Comment by deltazefiro** [comment]
Done. b3d5396971715817f9daf327e593d61971148dca
