### ISSUE TITLE
[FeatureRequest] 

### ISSUE THREAD

**Issue by theflopperguy** [deltazefiro/Amarok-Hider#181]
**Feature Description / 功能描述**
A clear and concise description of what you want to happen. / 请描述你想建议加入的新功能。

LSPatch support for the Xhide module. 

**Reason / 理由**
Please describe why this feature should be added. / 请描述为什么应该加入这个功能。

This would be a really cool addition for non rooted devices.

**Comment by deltazefiro** [comment]
Hi @theflopperguy 
Unfortunately, as a system-level hiding solution, XHide need to hook the system framework. 
LSPatch or other root free Xposed frameworks do not support that.
