### ISSUE TITLE
[FeatureRequest] App Intent to trigger Hide

### ISSUE THREAD

**Issue by SaadAhmedGit** [deltazefiro/Amarok-Hider#187]
**Feature Description / 功能描述**
An intent that can be called by other apps to trigger Amarok to hide apps and folders.

**Reason / 理由**
Many android automation apps can send intents to other apps. This would allow Amarok to be triggered with more custom conditions. For example, [KeyMapper](https://github.com/keymapperorg/KeyMapper) is an app that allows mapping physical key presses to certain actions and one of those actions is sending intents. This could be very helpful in a scenario where you're physically being forced to open up your phone such as routine police check ups in oppressive regimes.

**Suggest Solution / 实现方案**
If intent use can be scoped to certain apps only, that would make it more secure as it would only allow those external apps to trigger Hide that the user has allowed. Also, I am not sure but I think if Amarok is used in this way, it won't be necessary to keep it running in the background.

**Comment by deltazefiro** [comment]
Hi @SaadAhmedGit 
Have you checked out our [API docs](https://deltazefiro.github.io/Amarok-doc/en-US/api.html)? It might provide exactly what you're looking for.

**Comment by SaadAhmedGit** [comment]
> Hi @SaadAhmedGit 
> Have you checked out our [API docs](https://deltazefiro.github.io/Amarok-doc/en-US/api.html)? It might provide exactly what you're looking for.

No I hadn't . This is exactly what I was looking for. Thank you.
