### ISSUE TITLE
[FeatureRequest] ability to set a password on amarok

### ISSUE THREAD

**Issue by Wjxfi** [deltazefiro/Amarok-Hider#23]
**Feature Description / 功能描述**
A clear and concise description of what you want to happen. / 请描述你想建议加入的新功能。
ability to set a password on amarok
in the settings

**Reason / 理由**
Please describe why this feature should be added. / 请描述为什么应该加入这个功能。
it's much more private

**Comment by deltazefiro** [comment]
Already been on the [todo list](https://github.com/users/deltazefiro/projects/2?pane=issue&itemId=16998124) for a month. :laughing:

**Comment by deltazefiro** [comment]
Done. v0.8.4a1

**Comment by Turhvjbufv** [comment]
@deltazefiro close as completed please
