### ISSUE TITLE
[FeatureRequest] A way to Translate/Localise the app into other languages

### ISSUE THREAD

**Issue by SecularSteve** [deltazefiro/Amarok-Hider#29]
**Feature Description / 功能描述**
Basically, the ability to translate the application into any language of your choosing.

**Reason / 理由**
To make the app appeal to a wider audience, I want to translate it to German, Dutch and Serbo-Croatian (varieties included).

**Suggest Solution / 实现方案**
A ".po" folder, a self-hosted Weblate, or Instructions in the ReadMe or on the Site how to do it manually and make pull requests.

**Comment by deltazefiro** [comment]
Thanks for your support! :heart: 
Working on it.

**Comment by deltazefiro** [comment]
Done! [Hosted Weblate](https://hosted.weblate.org/engage/amarok-hider/)

**Comment by deltazefiro** [comment]
Closing the issue. Thanks!
