### ISSUE TITLE
it just changes the file name? I can also open these files and read what they say in the file explorer (txt, json, etc).

### ISSUE THREAD

**Issue by Wjxfi** [deltazefiro/Amarok-Hider#3]
it just changes the file name? I can also open these files and read what they say in the file explorer (txt, json, etc.)

can you shuffle the text files as specified in the header?

**Comment by deltazefiro** [comment]
Sorry for the delayed response.

Yes. Amarok just changes the filename.  
If you need to encrypt the whole file, please use encryption software.

**Comment by deltazefiro** [comment]
The feature is added in v0.8.1b1.  
Let me close this issue now. Feel free to reopen this issue if it does not work.  
Thanks again!

**Comment by deltazefiro** [comment]
Er... It does not work with text and zip files.   
Because It just changes the first several bytes of a file - the [file signature](https://en.wikipedia.org/wiki/List_of_file_signatures) - to make most of the file (video, music, image, apk etc.) corrupted.  
But a plain text file does not have a file signature. Shuffling the whole file is too costly.

**Comment by deltazefiro** [comment]
:thinking: Adding this feature is technically not a problem — But that will lose the purpose of this app.  
If you can endure the slow speed, why not use an encryption tool?  
It can surely be safer.

**Comment by deltazefiro** [comment]
Ahh. I know what you mean.  
Just make the text files fully shuffled.  
Sure, I'll add this feature soon.

**Comment by deltazefiro** [comment]
Hi Wjxfi,  
I've been implementing this feature recently, by setting up a file extension filter to select which file to be obfuscated.  
I'd like to know if the process only obfuscates the "conventionally speaking text" files - .txt, .md, etc., is that enough for you?  
Or you need it to fully obfuscate all "not-binary" files, like .xml .cfg .py .json etc.？

**Comment by deltazefiro** [comment]
> as I said before, it won't slow down the application because of the small file sizes.

Not really. Some users use Amarok to hide game files. That includes logs or generated configs, which can be very large.

> all non-binary. 

Another problem: I can't find a very accurate method way to distinguish whether a file is "binary" or not.  
MIME is a way, however it does not consistently produce reliable results. Not to mention using the file extensions.  

Anyway, though it may not work properly, try this: [Amarok-v0.8.1b3-foss-cabb47e.apk](https://mega.nz/file/XKxRTKQJ#NywyzgKPoTPC4F-NzCTs0HbH-cIodvuQlqeQP3inXT0)

Enable the switch `Fully Obfuscate Text File - Enhanced` in `More Settings > Switch FileHider Workmode`. The switch is visible only when you enable on `Obfuscate File Header` and `Fully Obfuscate Text File`.

**Comment by deltazefiro** [comment]
> when selecting this mode there will be a choice. All non-binary or this:

yep indeed that's what I've done :laughing:   
- `Fully Obfuscate Text File - Enhanced` tries to obfuscate all non-binary  
- While `Fully Obfuscate Text File` just obfuscate .txt and .md

And I also skip files larger than 10MB

**Comment by deltazefiro** [comment]
> I checked it out, it's just as fast and beautiful!

Good to hear! XD  

> we need to add more text formats

Could you provide a list MIME Types which are non-binary? Currently, I set it to obfuscate `text/*`.  
There may be some types that are left out: e.g. `application/x-python-code` for .py files.
I have to add these manually.

>  limit it to 30 MB

Tweaked!

**Comment by deltazefiro** [comment]
Oops I think you misunderstood. 
For `.epub`, `.docx` etc., obfuscating their headers is just enough. So they are "binary" ones.  
And for `.html` `.text` `.tex` etc., their MIME Types are already started with `text/*`.  

And I'm not using file extensions to check its type ... So MIME Type please if you find exceptions.

**Comment by deltazefiro** [comment]
Let's mark the issue as resolved!
