### ISSUE TITLE
[FeatureRequest] Hide function shotcut/ Tasker supporr

### ISSUE THREAD

**Issue by MA9008** [deltazefiro/Amarok-Hider#30]
**Feature Description / 功能描述**
A clear and concise description of what you want to happen. / 请描述你想建议加入的新功能
**It would be great to  add tasker/macrodroid support, or a direct shortcut to the hide function (that can work with auto tasks apps)so it can be triggered when needed in a rush without noticing, thanks**
**Reason / 理由**
Please describe why this feature should be added. / 请描述为什么应该加入这个功能。

**Suggest Solution / 实现方案**
(Optional) Possible ways to implement this feature / （可选）如果你已想出新功能的实现方案，请在这里写出。

**Comment by deltazefiro** [comment]
Hey @MA9008 
A cool suggestion! :laughing: However personally I'm not very familiar with tasker or Macrodroid - what shall I do to make them work together? Maybe I can set up an intent filter, so you can send an intent with your automation apps to trigger?

> so it can be triggered when needed in a rush without noticing, thanks

Hey actually there is a new feature I'm working on currently called "Panic Button". When you are in the "unhide" state, Amarok will create a floating button on your screen, over other apps. And when you click the panic button, Amarok will hide all the stuff! I plan to roll out this feature soon, maybe in the next pre-release :smiley:

**Comment by deltazefiro** [comment]
Hey @MA9008
I added a BroadcastReceiver. Try this CI version: [f7688ff](https://github.com/deltazefiro/Amarok-Hider/suites/11077446746/artifacts/563599576) (Login to GitHub to open the link, or you'll get a 404)

- Package: PackageID of Amarok, different versions have different IDs. For the CI build one: `deltazero.amarok.foss.debug`
- Class: `deltazero.amarok.ActionReceiver`
- Action:
  - `deltazero.amarok.HIDE` (hide)
  - `deltazero.amarok.UNHIDE` (unhide)

Instructions: [macrodroid](https://www.macrodroidforum.com/index.php?threads/how-to-use-action-send-intent.57/), [tasker](https://joaoapps.com/autoshare/intentbuilder/)

**Comment by deltazefiro** [comment]
I'd like to provide instructions in-app in the next major version.

**Comment by MA9008** [comment]
That's great news, thank you.
I will try and report if there's any bug..

**Comment by ironlungx** [comment]
Could you give a snippet on how to trigger it from an android application?

**Comment by deltazefiro** [comment]
@ironlungx Sure. Here is the snippet to trigger the hiding process:
```java
Intent intent = new Intent();
intent.setAction("deltazero.amarok.HIDE");
sendBroadcast(intent);
```
See [sending broadcasts section](https://developer.android.com/develop/background-work/background-tasks/broadcasts#sending-broadcasts) in the Android developer guide and [our action receiver](https://github.com/deltazefiro/Amarok-Hider/blob/main/app/src/main/java/deltazero/amarok/receivers/ActionReceiver.java#L16-L39) for reference.

**Comment by ironlungx** [comment]
thank you!

**Comment by deltazefiro** [comment]
> I'd like to provide instructions in-app in the next major version.

[Doc](https://deltazefiro.github.io/Amarok-doc/en-US/api.html) added. Mark this issue complete :)
