### ISSUE TITLE
请求不混淆.nomedia文件[FeatureRequest] 

### ISSUE THREAD

**Issue by dsgler** [deltazefiro/Amarok-Hider#31]
**Feature Description / 功能描述**
在混淆忘记时跳过.nomedia文件/文件夹

**Reason / 理由**
防止文件被媒体库记录

**Comment by deltazefiro** [comment]
嗯... 其实我认为媒体文件经 Amarok 混淆后，应当不会被媒体库识别为媒体文件了吧 :thinking:

**Comment by xz-dev** [comment]
开启修改文件头，就不用担心了

**Comment by dsgler** [comment]
混淆后好像是不会进媒体库，不过在我加.nomedia之前解除隐藏后被记录了。为了防止社死，可以建议用户加.nomedia？

**Comment by deltazefiro** [comment]
已修复。可以试试 [CI版本](https://github.com/deltazefiro/Amarok-Hider/actions/runs/4154241654)
