### ISSUE TITLE
[FeatureRequest] Display a notification to show hider state

### ISSUE THREAD

**Issue by CaffineAddic** [deltazefiro/Amarok-Hider#38]
**Feature Description / 功能描述**
A clear and concise description of what you want to happen. / 请描述你想建议加入的新功能。

###Notification showing that the vault is open/ unhidden 

**Reason / 理由**
Please describe why this feature should be added. / 请描述为什么应该加入这个功能。

#####Many times people forget to hide the files until it's too late because the files are visible, notification to constantly remind that the Amarok is allowing the files to be visible.

**Suggest Solution / 实现方案**
(Optional) Possible ways to implement this feature / （可选）如果你已想出新功能的实现方案，请在这里写出。

Sorry I wish I knew anything

**Comment by deltazefiro** [comment]
Closing. [v0.8.3a3](https://github.com/deltazefiro/Amarok-Hider/releases/tag/v0.8.3a3)
