### ISSUE TITLE
[FeatureRequest] Add Biometric unlock

### ISSUE THREAD

**Issue by HarriBuh** [deltazefiro/Amarok-Hider#39]
**Feature Description
Add a security layer in front of the app by adding the biometric unlock feature 

**Reason
The concept of the app becomes useless in the moment any other user accesses the Amarok app and simply clicks on "Unlock"

**Suggest Solution
I have seen this working well in other apps who also rely on privacy and FOSS.

**Comment by Aswin8** [comment]
+1
Using the device's biometric or a Pin lock similar to many other FOSS apps would make this app the best among all other alternatives.

**Comment by fedonr** [comment]
+1

**Comment by deltazefiro** [comment]
Biometric unlock & password unlock were added in v0.8.4a1.  
Thanks for the suggestion.
