### ISSUE TITLE
[BUG] App corruption

### ISSUE THREAD

**Issue by coolcart** [deltazefiro/Amarok-Hider#41]
**Describe the bug / 问题描述**
Amarok makes it possible to hide itself which makes all other hidden apps not recoverable

**To Reproduce / 复现步骤**
1. Hide some apps
2. Reinstall amarok
3. Apps are now forever hidden and have to be uninstalled from settings

**Additional context / 其他信息**
I've accidentally hidden amarok and with no way to unhide it, I tried to reinstall hoping that I would be able to recover my hidden apps, but amarok doesn't see them anymore

**Comment by deltazefiro** [comment]
> Amarok makes it possible to hide itself which makes all other hidden apps not recoverable

Er well it seems to be a bug. Let me have a check.

**Comment by deltazefiro** [comment]
Oops my bad. :fearful: Can I assume you are using v0.8.2-foss and hide with Shizuku? It's surely a serious bug only happens on foss version.

> Apps are now forever hidden and have to be uninstalled from settings

Made a quick fix. Please install the ci version.

**Comment by coolcart** [comment]
I set apphider mode to shizuku and performed hide and unhide but all of my apps are still disabled and are not displayed in amarok

**Comment by coolcart** [comment]
Also all apps previously hidden by amarok are displayed in system settings, but when i type `pm list packages` then for some reason no hidden packages are returned

**Comment by deltazefiro** [comment]
>  are not displayed in Amarok

Weird. They should be displayed in Amarok in the new version.
Anyway, seems that you have access to adb & your device is rooted, fix them manually:

```
$ fgrep -v -f <(adb shell pm list packages |sort) <(adb shell pm list packages -u|sort)
package:first.hidden.pkgname
package:second.hidden.pkgname
...

$ adb shell su -c "pm unhide first.hidden.pkgname & pm enable first.hidden.pkgname "
$ adb shell su -c "pm unhide first.hidden.pkgname & pm enable second.hidden.pkgname "
...
```

**Comment by coolcart** [comment]
It returns an error
`1|taimen:/ # fgrep -v -f <(adb shell pm list packages |sort) <(adb shell pm list packages -u|sort)`
`/system/bin/sh: syntax error: unexpected '('`

**Comment by coolcart** [comment]
Never mind it works now

**Comment by HarriBuh** [comment]
This also happens when working with root mode. I tried the same out of curiosity and the outcome was the same

**Comment by deltazefiro** [comment]
> This also happens when working with root mode. I tried the same out of curiosity and the outcome was the same

Um which outcome? Does that mean you can still find Amarok in the latest CI build version (in the latest pre-release the bug should persist, as it was released yesterday)? Or "performed hide and unhide but all of my apps are still disabled"?

**Comment by HarriBuh** [comment]
Nah, I could "hide" Amarok within Amarok and it would ofc left disabled and so all the other apps. I was referring to this.

**Comment by deltazefiro** [comment]
Are you sure you are using `v0.8.3a2-571c330-foss` — the latest ci version?
Amarok itself should disappear from the `Set Hidden Apps` menu, so it can not disable itself. Does this work as expected?

**Comment by HarriBuh** [comment]
No, just like I wrote previously. I'm using the latest stable version of 0.8.2 available on Fdroid. So basically you want me to try and testify whether this big still persists on your least pre-realease.. I'm gonna check this right now and report back.

**Comment by deltazefiro** [comment]
No, perhaps you misunderstood. :thinking: 

> in the latest pre-release the bug should persist, as it was released yesterday

I mean it is fixed in the CI Build version `v0.8.3a2-571c330-foss` - not even in the pre-release `v0.8.3a2` or release `v0.8.2`.
You can download the CI build version [here](https://github.com/deltazefiro/Amarok-Hider/suites/10844124531/artifacts/546348197). :wink:

**Comment by deltazefiro** [comment]
> Btw, the link you provided won't work- it gives me an 404-error.

oh my! really? I can open it — did you log in? Maybe you need to log in to GitHub to download, or you'll get a 404.
Or you can get it on [mega](https://mega.nz/file/HaI1SKCZ#URWsMBWNWhKLqEBGOdGfmY89fgRSy0shgjrM-uhkqqY).

**Comment by deltazefiro** [comment]
Close then
