### ISSUE TITLE
[Help] I did also hide the app itself, now everything that's hidden cannot be recovered.

### ISSUE THREAD

**Issue by IceAsteroid** [deltazefiro/Amarok-Hider#43]
Any ways of recovering at least the files of hidden apps'?

Did it because it's not completely hidden, as the app itself is still there & with partially out of curiosity.

I never knew it would end up this bad,  I hate myself, I'm sorry, guys. :(

System: LineageOS, version 19-20220721-NIGHTLY-taimen, based on Android 12.

Any helps?

**Comment by deltazefiro** [comment]
#41

**Comment by IceAsteroid** [comment]
> #41

It actually works. So much thanks!

Just select  ones that had been hidden, to hide & unhide again, with the version of Amarok that's posted in #41 by the Owner.

**Comment by IceAsteroid** [comment]
@deltazefiro Should this issue be closed or still open for those who also encounter this problem?

**Comment by deltazefiro** [comment]
Closing it. But let me pin this issue :)

**Comment by IceAsteroid** [comment]
ok
