### ISSUE TITLE
[Question] Why this app is connected to internet even if auto update is disabled 

### ISSUE THREAD

**Issue by jerryn70** [deltazefiro/Amarok-Hider#46]
Today I saw this app in fdroid and downloaded it for testing. In less than 5 mins of usage this app consumed 36.99 Mb of mobile data. Why that happens ? What data has been collected or sent to somewhere? 

Note : Auto update and analytics options are disabled

**Comment by deltazefiro** [comment]
...uh? Are you sure?
But the foss ver doesn't even request for the internet permission!

**Comment by jerryn70** [comment]
@deltazefiro ![](https://i.imgur.com/0tirecK.png)

**Comment by deltazefiro** [comment]
Which version are you using? Did you download it directly from fdroid?

**Comment by jerryn70** [comment]
@deltazefiro version 0.8.2 downloaded from fdroid

**Comment by deltazefiro** [comment]
@jerryn70 That's impossible!
Check this: [No internet permission](https://beta.pithus.org/report/224b25543b46463837e44b97b65b5c7f2c32f0d8346505a9d66b336076b3ade8) & [In-app link analysis](https://beta.pithus.org/report/224b25543b46463837e44b97b65b5c7f2c32f0d8346505a9d66b336076b3ade8)

**Comment by deltazefiro** [comment]
Perhaps a bug of Nothing OS. On my MIUI it's zero.
![1676108351548](https://user-images.githubusercontent.com/41465688/218251335-0bbd544e-e8c7-42d9-8a5e-f4e995bbb9ac.png)

**Comment by jerryn70** [comment]
@deltazefiro maybe. Now I just uninstalled and reinstalled the app now it's showing zero.

**Comment by deltazefiro** [comment]
Close the issue then. We'll never collect any info from you with foss version.
