### ISSUE TITLE
[FeatureRequest] Hide system apps

### ISSUE THREAD

**Issue by zhanghunuaa** [deltazefiro/Amarok-Hider#47]
**Feature Description / 功能描述**
my phone's OS is MIUI14, and system apps or MIUI's apps are not shown in amarok's app list. so is that possible to add these apps to list to hide?

**Reason / 理由**
some MIUI's apps are not comfortable to use.

**Comment by deltazefiro** [comment]
@zhanghunuaa :clap: 
Amarok filtered out system apps on purpose. We strongly discourage you from hiding system apps — especially on MIUI — as that may cause your device to fail to boot.

> some MIUI's apps are not comfortable to use.

Amarok is not an app freezer, though they work by the same mechanism. It is a tool to hide apps you may feel uncomfortable showing to others, and unhide them when you are on your own. I don't see why you feel uneasy to show others a system app. I'd like to recommend [Hail](https://github.com/aistra0528/Hail) if you just want to freeze (disable) apps.

**Comment by zhanghunuaa** [comment]
@deltazefiro hail is what exactly i need.thank you

**Comment by zhanghunuaa** [comment]
try hail
