### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by marcossmtp** [deltazefiro/Amarok-Hider#48]
**Describe the bug / 问题描述**
When I use samsung s7 android 8 rooted with microsd persmission enabled, it only ofuscated files in the internal storage,
For some reason it says that directory selected in microsd is hide but the name of the files are not ofuscated.

I agree too with two other person who proposed use biometrical to access app (in other case too simple to desofuscate), and a option to integrate with tasker macrodroid (plugin) to offuscate for example in remote with webhooks (macrodroid allow that and it should be great.

Thanks

**Comment by deltazefiro** [comment]
> When I use samsung s7 android 8 rooted with microsd persmission enabled

#17

> I agree too with two other person who proposed use biometrical to access app 

WIP. I'll roll them out in v0.8.4.

> integrate with tasker macrodroid (plugin) 

Perhaps not plugins, but I'm ready to set up an intent filter — I'll provide instructions on how to integrate it with Tasker and Macrodroid.

I'd like to close this issue, as it includes 3 open issues. Just comment on those issues.
