### ISSUE TITLE
I can't download the app in f-droid

### ISSUE THREAD

**Issue by Wjxfi** [deltazefiro/Amarok-Hider#5]
it writes android.software.leanback is required to install the application

**Comment by deltazefiro** [comment]
Fixed.  
The permission `android.software.leanback` was for hiding Amarok from the launcher on Android 9.

**Comment by deltazefiro** [comment]
Fixed in release v0.8.1b1.  
Let me close this issue now. Feel free to reopen this issue if it does not work.
