### ISSUE TITLE
[FeatureRequest] Support Themed Icon

### ISSUE THREAD

**Issue by xmha97** [deltazefiro/Amarok-Hider#50]
Please support the Themed Icon.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

![Screenshot_2023-02-20-15-49-44-737_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220105408-c7de6f54-c794-4f5c-af5a-b17da10e25ac.jpg)

Thanks.

**Comment by deltazefiro** [comment]
Done. [apk built by ci](https://github.com/deltazefiro/Amarok-Hider/suites/11244553283/artifacts/575910786).

**Comment by xmha97** [comment]
Thanks 🙏
I'm waiting for the stable version.

**Comment by deltazefiro** [comment]
Closing stale issue. Comment below if necessary.
