### ISSUE TITLE
[FeatureRequest] Pull files to be obfuscated by "last modified" attribute

### ISSUE THREAD

**Issue by TheRetenor** [deltazefiro/Amarok-Hider#52]
**Feature Description / 功能描述**
Add an option to make Amarok obfuscate file names in the order they were last modified.

**Reason / 理由**
This would ensure files being able to be displayed in the order they were created or modified.
Especially useful for document / download / etc. folders where the most recent files are mostly those being looked for.
Currently Amarok will shuffle the affected folders and makes it hard to find files.

**Suggest Solution / 实现方案**
Maybe implement a function to pull files via FileTime lastModifiedTime() and obfuscate from oldest to newest per affected folder.

**Comment by deltazefiro** [comment]
File obfuscation now preserves the original last modified time by default since v0.8.4a1.  
Thank you for your feedback.
