### ISSUE TITLE
Invalid DSM provider

### ISSUE THREAD

**Issue by Wjxfi** [deltazefiro/Amarok-Hider#6]
How do I find the right one? There is no selection of DSM providers

**Comment by deltazefiro** [comment]
Amarok use [Delegated-Scopes-Manager](https://github.com/heruoxin/Delegated-Scopes-Manager), which only allows one DSM provider per Android device.   
Please follow the [tutorial](https://deltazefiro.github.io/Amarok-doc/hideapp.html#dsm%E6%A8%A1%E5%BC%8F) (Chinese) to configure DSM provider.  

Note that DSM mode is not recommended and may be deprecated in the next release.   
Instead, use [Root Mode](https://deltazefiro.github.io/Amarok-doc/hideapp.html#root%E6%A8%A1%E5%BC%8F) if your device is root or [Shizuku Mode](https://deltazefiro.github.io/Amarok-doc/hideapp.html#shizuku%E6%A8%A1%E5%BC%8F) if not.

**Comment by deltazefiro** [comment]
I suppose this has been resolved. Feel free to reopen it if you still need more assistance.
