### ISSUE TITLE
[FeatureRequest] 添加保留文件原始日期功能

### ISSUE THREAD

**Issue by Jialin0502** [deltazefiro/Amarok-Hider#61]
**Feature Description / 功能描述**
添加 保留文件的原始修改日期 开关
对隐藏文件进行还原后，时间可以恢复为当初时间

Added keep original modification date of files switch
 After restoring the hidden files, the time can be restored to the original time

**Reason / 理由**
进行文件还原操作，时间会变成当前时间，而原始日期被刷新，导致需要时间先后文件的顺序被打乱

When the file restoration operation is performed, the time will become the current time, and the original date will be refreshed, causing the order of the files that need to be chronologically disrupted

**Suggest Solution / 实现方案**
文件原始日期保存方法 1.直接包含在混淆后的文件名中 2.写入文件头

Original date preservation method 1. Directly included in the obfuscated file name 2. Write to the file header

**Comment by deltazefiro** [comment]
v0.8.4a1 后文件混淆将不改变文件修改日期。
感谢建议。
