### ISSUE TITLE
Problem at unhide the files while Amarok itself  has app lock feature on![BUG] 

### ISSUE THREAD

**Issue by AmirrezaG** [deltazefiro/Amarok-Hider#78]
after you enable the app lock feature of the Amarok, you shouldn't be able to unhide the files from another way or at least it must require identification or something like that. so you should fix this problem with Amarok's quick panel button because after is hide my contents , i can easily uhide them using button at the quick panel layout (1)  without any need for authentication. 

(1) button i meant 
![Screenshot_20230707_183318_Firefox](https://github.com/deltazefiro/Amarok-Hider/assets/50150879/3aace500-588a-4e53-8dee-4ceec98553b9)

**Comment by deltazefiro** [comment]
Hi @AmirrezaG  
Which version of Amarok are you using? The issue should have been fixed in v0.8.4a2.

**Comment by AmirrezaG** [comment]
> Hi @AmirrezaG Which version of Amarok are you using? The issue should have been fixed in v0.8.4a2.

hi , yeah just updated mine. it works like a charm now ✨️. thanks 👍🏻
