### ISSUE TITLE
how to hide/unhide via shell ？

### ISSUE THREAD

**Issue by falcolee** [deltazefiro/Amarok-Hider#8]
like some onekey things do, hide apps or files in one second in case of emergency, the it can be started from a shortcut on a rooted device, i am searching for "am start" command, but not sure how to do hide action, any idea ? thanks for your nice work

**Comment by deltazefiro** [comment]
我用中文与您沟通吧。  
> like some onekey things do ... i am searching for "am start" command, but not sure how to do hide action

如果我没有理解错的话，您希望通过某个自动化程序使用 `adb shell am start` 调用 Amarok 完成一键隐藏。  
很抱歉，但目前 Amarok 并没有这样一个特定的 Activity，接收到 intent 就进行隐藏/取消隐藏。

不过，Amarok 目前提供一个 `QuickSetting` 开关 (控制面板开关) 用于一键隐藏。您可以尝试找一下您使用自动化程序是否支持自动开关控制面板中的开关。

**Comment by falcolee** [comment]
谢谢回应，原来本身有快捷开关功能，已经用上了~~~找到了一个启动命令如下:
`am start -a android.intent.action.MAIN -e action "hide" -n deltazero.amarok/.ui.ShortcutActivity`
ShortcutActivity.java代码如下
```
public class ShortcutActivity extends AppCompatActivity {

    public final static String TAG = "Shortcut";

    private Hider hider;
    private PrefMgr prefMgr;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // Init
        super.onCreate(savedInstanceState);
        hider = new Hider(this);
        prefMgr = hider.prefMgr;

        String actionExtra = getIntent().getStringExtra("action");
        if (actionExtra == null) {
            actionExtra = "hide";
        }

        if (actionExtra.equals("unhide")) {
            if(prefMgr.getIsHidden()){
                hider.syncUnhide();
            }
        } else {
            if(!prefMgr.getIsHidden()){
                hider.syncHide();
            }
        }
        this.finish();
    }

    @Override
    protected void onResume() {
        super.onResume();
    }

}
```
希望能对后来人有帮助哈，再次感谢楼主
