### ISSUE TITLE
Fastlane changelog too long

### ISSUE THREAD

**Issue by IzzySoft** [deltazefiro/Amarok-Hider#84]
Fastlane changelogs are limited to 500 char. `51.txt` for `en-US` has 612 chars. Please take care to stay in the limits :wink: Thanks!

**Comment by deltazefiro** [comment]
Oh my, I hadn't noticed that before! :astonished:   
I'll take care of it. Thanks.

**Comment by IzzySoft** [comment]
I didn't notice either, my scanner informed me on its monthly "quality check" :see_no_evil: Thanks for taking care!

**Comment by IzzySoft** [comment]
@deltazefiro looks like you forgot again:

```
deltazero.amarok.foss/metadata/en-US/changelogs/120.txt has 556 chars
deltazero.amarok.foss/metadata/en-US/changelogs/123.txt has 1022 chars
```

I've removed the former, and truncated the latter to cover the version served (i.e. removed the text for the other two versions). But please, take care for this with future releases. Maybe [this Github action](https://github.com/ashutoshgngwr/validate-fastlane-supply-metadata) can help you with it?
