### ISSUE TITLE
Could Amarok hide applications from system fields with root?

### ISSUE THREAD

**Issue by CompeyDev** [deltazefiro/Amarok-Hider#85]
Would it be possible for Amarok to hide applications within system fields such as the "Apps" list in settings, or the sharing menu, or permissions area?

I believe OnePlus' OxygenOS goes about hiding it from the apps list but not the other aforementioned locations...

**Comment by deltazefiro** [comment]
Hi @CompeyDev! 👏  
In theory, with `Root` or `Shizuku/Sui` mode, the hidden apps should not appear anywhere in the system menu.  
Are you sure that you are using these modes?  
I haven't tested this on OxygenOS, but it works fine on vanilla Android and MIUI.

**Comment by CompeyDev** [comment]
> Hi @CompeyDev! 👏
In theory, with Root or Shizuku/Sui mode, the hidden apps should not appear anywhere in the system menu.
Are you sure that you are using these modes?
I haven't tested this on OxygenOS, but it works fine on vanilla Android and MIUI.


Hey! Thanks for the quick response; I created this issue before actually installing the app - in order to see if it would match my use case, and it works just as expected. Works fine on OxygenOS as well as vanilla.
