### ISSUE TITLE
[FeatureRequest] Obfuscate folder names

### ISSUE THREAD

**Issue by Jasper1467** [deltazefiro/Amarok-Hider#92]
**Feature Description / 功能描述**
An option so hidden folders also have obfuscated names.

**Reason / 理由**
The name of the folders can give away the content of the folder.

**Suggest Solution / 实现方案**
Same as the current obfuscating file names system but for folders

**Comment by deltazefiro** [comment]
Amarok does obfuscate the names of the folders - except for the outermost folder.  
We keep the name of the outermost folder fixed to prevent clutter in the storage.

**Comment by Jasper1467** [comment]
Thanks for clarifying! I'm closing the issue.
