### ISSUE TITLE
App is sold in AppGallery 

### ISSUE THREAD

**Issue by Lijucay** [deltazefiro/Amarok-Hider#96]
Hey Dev,

I am sorry for telling you but your app has been stolen by some unknown person and it is sold on AppGallery.

![Screenshot_2023-09-21-18-55-24-599_com.huawei.appmarket.jpg](https://github.com/deltazefiro/Amarok-Hider/assets/104652374/69ac7c91-ecbf-489f-b33c-cd089af35704)

**Comment by deltazefiro** [comment]
Hi @Lijukay,
Thank you for reporting this to me. I am currently investigating the matter.  
Could you provide me with the link to the app page on the AppGallery?

**Comment by Lijukay** [comment]
Sure. Here is the link to the app in AppGallery:

https://appgallery.cloud.huawei.com/ag/n/app/C108358265?locale=en_US&source=appshare&subsource=C108358265&shareTo=com.android.bluetooth&shareFrom=appmarket&shareIds=11fbef4d7b084706b43a251538f63265_com.android.bluetooth&callType=SHARE

**Comment by deltazefiro** [comment]
Seems that the link is region-restricted as I can only view an empty page with the message "No apps".   

I checked the Apache license and found that it permits commercial use and redistribution (I am not a layer, correct me if I am wrong) :disappointed: There are really few things we can do.   

In the next version of the app, I plan to include a notification that informs the user that they are using a free application. If you have any better suggestions, kindly inform me.

**Comment by Lijukay** [comment]
Hello there,

I am sorry to hear that.


I am affected myself and after a long discussion with some friends of mine, I decided to use another license. However, the notification is a very good idea. This way, the user is informed.

**Comment by deltazefiro** [comment]
A notification will pop up to notify the user that they are using a free and freedom application in v0.8.5a2.  
The Apache license forbids the modifier from removing it. I hope this will work.

**Comment by PhilippFrigerio** [comment]
![Screenshot_2023-10-19-12-28-26-259_com huawei appmarket](https://github.com/deltazefiro/Amarok-Hider/assets/146529492/df060539-35bb-439f-a799-d98802980882)
![Screenshot_2023-10-19-12-30-11-638_com huawei appmarket](https://github.com/deltazefiro/Amarok-Hider/assets/146529492/66983942-ae1a-40a3-a237-615ec32ad80f)

This guy is currently selling over 100 apps on AppGallery, probably stolen too!? I hate such outrageous people. You could complain to Huawei.

**Comment by Lijukay** [comment]
I did that. The license does, as previously mentioned, not forbid such things. However, I am thinking of uploading my app to the app gallery myself. Since it might result in a conflict (since there is already such an app), his version will probably get deleted since I can verify that I am the developer of my app. I am not sure if deltazefiro wants to do that as well, but his warning and idea of adding a notification should be enough.

**Comment by Lijucay** [comment]
> > This guy is currently selling over 100 apps on AppGallery, probably stolen too!? I hate such outrageous people. You could complain to Huawei.
> 
> I also saw PipePipe there, I can't believe he's dumping open source software that isn't its own

Is it still online? I can't check it, since for me, the results are empty

**Comment by I21b** [comment]
> > > This guy is currently selling over 100 apps on AppGallery, probably stolen too!? I hate such outrageous people. You could complain to Huawei.
> > 
> > I also saw PipePipe there, I can't believe he's dumping open source software that isn't its own
> 
> Is it still online? I can't check it, since for me, the results are empty

The last time I saw it was months ago, looks like it's been reported now. (satisfying)

**Comment by lazy-pupp** [comment]
=I was just wondering if you agreed with Knoppix Team about using Ak as,
get this now, not as Tomb player but WMP replica. I got so confused... It's
a smart Debian distro, penlinux university academia recomended on //lss.hr/.
So I was wondering how it works on a12 distro. Just fine :-)
Thank u experienc3d crew for letting us teachers learn how to "look under
the hub". Oric Nova64 programming out of boardom guy aka - me. People get
desperate, but respect is relevant and I cite my sources. I.P. Zagreb,
Croatia,

Dana petak, 17. svibnja 2024. 92 ***@***.***> piše:
