### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Krishanth1** [deltazefiro/Amarok-Hider#97]
**Describe the bug / 问题描述**
I can still access hidden app from play store.
请清晰地描述您遇到的异常。

**To Reproduce / 复现步骤**
Steps to reproduce the behavior / 复现异常的步骤:
1. Go to 'play store'
2. Click on 'enable'
3. Click on open
4. App is opened

**Expected behavior / 预期行为**
Should not open.
描述您认为正常情况下应该发生什么。

**Screenshots / 截图**
（可选）问题复现时候的截图或录屏。

**Basic Information (please complete the following information) / 请填写以下信息:**
 - OS (ROM) / 系统: realme color os
 - Android Version / 13.5
 - Amarok Version / Amarok版本: 0.8.5a1

**Additional context / 其他信息**
在这里输入其他有关此异常的信息。

**Comment by deltazefiro** [comment]
Without root, we have no way to hide the app from the app store.  
If you have any suggestions on how to accomplish this, please inform me.
